### ISSUE TITLE
Solution Branch (ex 4) should have a manual instance

### ISSUE THREAD

**Issue by lsmor** [lsmor/snake-fury#7]
Implement Manual instances for `newtype` in the solution branch as commented in [this](https://github.com/lsmor/snake-fury/pull/6#issuecomment-1444729125) comment

**Comment by lsmor** [comment]
Fixed on [this](https://github.com/lsmor/snake-fury/commit/dd146a59289e88b865bf7c2a2fe4a014f2896bab) commit. 

@slowdive-, based on your feedback I've added manual instances for `GameState` to `solution-refactor-4` and higher. Indeed it turned out to be a little bit more difficult than expected, due to the high level of abstraction It is easy to mess things up. Thanks por pointing this out

**Comment by slowdive-** [comment]
Thanks! These really do help, I definitely overcomplicated things in some places.
